# Generated by Django 5.2.5 on 2025-09-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='last_attended',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
