# Generated by Django 5.2.5 on 2025-11-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_studentrequest_last_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='request_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
