# Generated by Django 5.2.5 on 2025-11-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studentrequest_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
