# Generated by Django 5.2.5 on 2025-09-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_studentrequest_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrequest',
            name='created_by',
        ),
    ]
