# Generated by Django 5.2.5 on 2025-11-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentrequest_payment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='claim_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
