# Generated by Django 5.2.5 on 2025-11-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_studentrequest_claim_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='request_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('to pay', 'To Pay'), ('confirmed', 'Confirmed'), ('released', 'Released'), ('rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
