# Generated by Django 5.2.5 on 2025-11-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_studentrequest_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('To Pay', 'To Pay'), ('Confirmed', 'Confirmed'), ('Released', 'Released'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
