# Generated by Django 5.2.5 on 2025-11-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_studentrequest_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='request_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
