# Generated by Django 5.2.5 on 2025-09-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentrequest',
            name='year_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]