# Generated by Django 5.2.5 on 2025-11-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_studentrequest_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
